# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memeria' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memeria
  pod 'Moya/RxSwift', '~> 13.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'RxSwift', '~> 4'
  pod 'RxCocoa', '~> 4'

  target 'MemeriaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemeriaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
